name: 'responder'
description: 'Creates a issue comment when the issue is labeled'
inputs:
  allowedUser:  # id of input
    description: 'Changes the response for the allowed user'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
